version: '3.1'

services:

  rproxy:
    container_name: wp-nginx
    build:
      context: https://github.com/teruo41/Dockerfiles.git#:wordpress-nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress:/var/www/html
      - nginx-log:/var/log/nginx
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:6.4.2-fpm-alpine
    restart: always
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: mywordpress
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
      - wordpress-log:/var/log
    depends_on:
      - db

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: mywordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - db-log:/var/log

volumes:
  wordpress:
  nginx-log:
  log:
  db:
